### ISSUE TITLE
Add descriptions network cards

### ISSUE THREAD

**Issue by michelleellen** [gnolang/faucet-hub#22]
## Description

As discussed on Slack, we should add a short description for each network card for providing a bit more details. Below are text snippets that we can add for the current/upcoming networks.

### Gno Portal Loop
A nightly staging testnet used for experimenting with the latest versions of Gno, Gno.land, and TM2.
### Gno Staging
A staging testnet which is reset regularly, used for testing automation, single-use code, and demoing.
### Flippando
A fully on-chain [memory game](https://gno.flippando.xyz/flip) built on top Gno.land.

cc: @leohhhn

**Comment by leohhhn** [comment]
Closed in https://github.com/gnolang/faucet-hub/pull/24
