### ISSUE TITLE
Staging improvements

### ISSUE THREAD

**Issue by leohhhn** [gnolang/faucet-hub#23]
## Description

Since staging.gno.land is reset on a regular basis meaning the balances are also wiped, it might make sense to set up a countdown timer on the network card, to warn users. Later we can also think about automating a faucet request for previous users of staging so that the UX is smooth (right now, users will have to request new funds after every reset). This is partly a Faucet Hub thing, and partly the infra side for staging.

**Comment by zivkovicmilos** [comment]
Closing this issue as it's not super relevant, and very use-case specific. How would the countdown even work?
We don't have enough traffic to justify dev time on this
