### ISSUE TITLE
Faucet Hub UI Improvements 

### ISSUE THREAD

**Issue by leohhhn** [gnolang/faucet-hub#27]
From Slack:

1. We could add buttons/items to the top right corner of the page to make it seem less empty - these could be the Gno homepage, Docs, Playground, and possibly later a "Connect wallet" button that will then automatically read the address to send coins to

2. Apart from that, we can have a CTA for people to add their faucets to the Hub. I suggest this to be a button which leads to a separate page giving simple and clear instructions on how to do this (I can help with this, just need 
 for the design/making of the page). The button could read "Add your faucet", "Running a Gno Faucet?", etc. However, I wouldn't necessarily put this as an eye-poking CTA, since the faucet hub is primarily aimed at devs looking for GNOTs, and secondly for faucet/chain runners.

**Comment by michelleellen** [comment]
Adding to this the snippets for Staging and dSocial are cut off 

![image](https://github.com/gnolang/faucet-hub/assets/117160070/adef4d41-8636-4dee-a87d-f927b07e292a)

**Comment by hiroyukikumazawa** [comment]
Sent pr - https://github.com/gnolang/faucet-hub/pull/30

**Comment by hiroyukikumazawa** [comment]
https://deploy-preview-30--gno-faucet-hub.netlify.app/

**Comment by hiroyukikumazawa** [comment]
hi @alexiscolin 
can we chat on discord?
terratinker is my discord username

**Comment by hiroyukikumazawa** [comment]
is there any other requirements?

**Comment by alexiscolin** [comment]
I keep this issue open since I'm gonna produce a design for the second part of it.

**Comment by hiroyukikumazawa** [comment]
if you need my help, feel free to ping me

**Comment by zivkovicmilos** [comment]
@alexiscolin any updates on this? 👀

**Comment by zivkovicmilos** [comment]
@alexiscolin 
We should probably just add a `CONTRIBUTING.md`, or make it apparent in the README on how to contribute a faucet
