### ISSUE TITLE
[v1] Develop front-end + review

### ISSUE THREAD

**Issue by waymobetta** [gnolang/faucet-hub#6]
Similarly to #3 , following the [wireframe/mock-up](https://github.com/gnolang/faucet-hub/issues/5) development, we'll need to expand on front-end functionality.

TODO:
- [ ] initial version
- [ ] review

**Comment by alexiscolin** [comment]
@zivkovicmilos @waymobetta  I just pushed my first draft. No real faucet request yet and no mobile version yet. Also, some optimization should be done to avoid DRY and improve SOLID principles. 
But the UI is here 🔥🔥🔥

A deploy preview from Netlify could be great by the way 👍

**Comment by waymobetta** [comment]
@alexiscolin Wow, this looks awesome! The transitions and animations are fluid and the flow is intuitive and clear, well done. Unfortunately, I'm not longer involved with the project but I trust that it is in good hands. Stay well, my friends.

**Comment by waymobetta** [comment]
@zivkovicmilos I guess only thing left to mention would be to determine whether this work was for v0 or for v1; see [related issue for v0](https://github.com/gnolang/faucet-hub/issues/3). The scope for v1 originally contained security countermeasures + [some improvements (like support for Adena)](https://github.com/gnolang/faucet-hub/milestone/2) though not sure if this has been since changed.
